[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "solmate/=lib/solmate/src/",
  "forge-std/=lib/forge-std/src/"
]

# Exclude test files from libraries
exclude = [
  "lib/openzeppelin-contracts/test",
  "lib/openzeppelin-contracts/fv",
  "lib/solmate/test"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
